name: NSPY
favicon: null
layout_spectrum: 0.25371232093311846
typography_spectrum: 0.39953784784302115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7062735073268414
  lightness: 0.1275607894640416
  saturation: 0.8886854390148073
  rhythmicContrast: 0.7889917760621756
purpose: []
